from util import log
from pathlib import Path
import json


def generate_project(path):
    path = Path(path)
    if path.exists():
        log(f'project "{path}" already exists')
        return
    path.mkdir()
    text_write = "# Generated by markdown-compiler\n## github\n- [GitHub](<!--{v-github}-->)"
    path.joinpath('main.md').write_text(text_write)
    json_write = {
        "github": "https://github.com/WwwwwyDev/markdown-compiler"
    }
    path.joinpath('main.json').write_text(json.dumps(json_write))
